//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ReporteSaldosCostos
    {
        public long Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> SaldoCosto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
