//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpDBEntities : DbContext
    {
        public ErpDBEntities()
            : base("name=ErpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Currencys> Currencys { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<MovementsAccountsReceivable> MovementsAccountsReceivable { get; set; }
        public virtual DbSet<MovementsDebtsToPay> MovementsDebtsToPay { get; set; }
        public virtual DbSet<MovementsInventory> MovementsInventory { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<RolUsers> RolUsers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<TipoCambio> TipoCambio { get; set; }
        public virtual DbSet<Inv_ReporteSaldos> Inv_ReporteSaldos { get; set; }
        public virtual DbSet<Inv_ReporteSaldosCostos> Inv_ReporteSaldosCostos { get; set; }
    }
}
