//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementsInventory
    {
        public int CompanyId { get; set; }
        public long InventoryMovementId { get; set; }
        public short DocumentTypeId { get; set; }
        public long ProductId { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime MovementDate { get; set; }
        public System.DateTime MovementLogDate { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<short> CostCurrencyId { get; set; }
        public Nullable<short> UnitPriceCurrencyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Currencys Currencys { get; set; }
        public virtual Currencys Currencys1 { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
