//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementsDebtsToPay
    {
        public int CompanyId { get; set; }
        public long DebtsToPayId { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public short DocumentTypeId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Currencys Currencys { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}
