//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int CompanyId { get; set; }
        public int ParameterId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Details { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
