//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.MovementsInventory = new HashSet<MovementsInventory>();
        }
    
        public int CompanyId { get; set; }
        public long ProductId { get; set; }
        public string Name { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitCost { get; set; }
        public Nullable<short> UnitCostCurrencyId { get; set; }
        public Nullable<short> UnitPriceCurrencyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Currencys Currencys { get; set; }
        public virtual Currencys Currencys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementsInventory> MovementsInventory { get; set; }
    }
}
