//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ErpFidelitas.General.v2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public long Consecutivo { get; set; }
        public int Cod_IndicadorInterno { get; set; }
        public System.DateTime Des_Fecha { get; set; }
        public decimal Num_Valor { get; set; }
    }
}
